### ISSUE TITLE
You can do stuff without logging in and it breaks everything

### ISSUE THREAD

**Issue by wingfield4** [madkins37/forum-project#3]

**Comment by wingfield4** [comment]
Like create a thread and post a comment. It triggers some PHP errors. If this doesn't get fixed, we can just be careful during our presentation, I don't think it'll be a big deal.

**Comment by omilam** [comment]
Yeah, I agree. I don't think the demo has to be that long.

**Comment by wingfield4** [comment]
fixed enough to present
